name: Deploy

on:
  push:
    branches:
      - main  # Set a branch to trigger deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Create CNAME
        run: echo 'www.poodlescheduler.com' > dist/CNAME

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages  # The branch the action should deploy to.
          folder: dist  # The folder the action should deploy
          clean: true  # Automatically remove old files from the deployment branch
          token: ${{ secrets.GITHUB_TOKEN }}  # GitHub automatically creates a `GITHUB_TOKEN` secret to use in your workflow.
          