name: Deploy

on:
  push:
    branches:
      - master  # Set a branch to trigger deployment

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          cd frontend
          npm ci

      - name: Build
        run: |
          cd frontend
          npm run build

      - name: Create CNAME
        run: echo 'www.poodlescheduler.com' > frontend/dist/CNAME

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages  # The branch the action should deploy to.
          folder: frontend/dist  # The folder the action should deploy
          clean: true  # Automatically remove old files from the deployment branch
          token: ${{ secrets.GITHUB_TOKEN }}  # GitHub automatically creates a `GITHUB_TOKEN` secret to use in your workflow.

